### ISSUE TITLE
Calls to RED.util.evaluateJSONataExpression must include a callback

### ISSUE THREAD

**Issue by danimart1991** [danimart1991/node-red-nodes#2]
Radarr and Sonarr nodes cause an error when use JSONata Expression to filter movies.

"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

Error
    at evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at Object.evaluateNodeProperty (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:673:18)
    at RadarrApiMovieEditorPutNode._inputCallback (/data/node_modules/@danimart1991/node-red-radarr-api/nodes/radarr-api-movieeditor.js:30:46)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at RadarrApiMovieEditorPutNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at RadarrApiMovieEditorPutNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at RadarrApiMovieEditorPutNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:494:10)
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:799...

**Comment by danimart1991** [comment]
Fixed in:
- Docker 0.1.5
- Sonarr-API 0.8.5
- Radarr-API 0.8.5
